### ISSUE TITLE
TODO: re-enable CI on Windows

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaLinearAlgebra/Octavian.jl#22]
The CI jobs on Windows are taking much longer than the Linux and macOS jobs. So I have disabled the Windows jobs for now.

Perhaps it's the specific CPUs that the Windows jobs are running on?

Maybe we could detect those CPUs, and run the tests with smaller matrices on those CPUs?

**Comment by DilumAluthge** [comment]
Or maybe Windows itself is the problem, in which case we could (in the test suite) detect if it is Windows, and then run the tests with smaller matrices if we are on Windows.

**Comment by chriselrod** [comment]
Currently, the matrices are 2x the size of `Octavian.block_size`. Only slightly larger would be fine.

**Comment by DilumAluthge** [comment]
Let's run the jobs and see what the runtimes and CPUs are for the Windows jobs.

https://github.com/JuliaLinearAlgebra/Octavian.jl/pull/23
