### ISSUE TITLE
De-conflicting the names of functions for matrix multiplication

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaLinearAlgebra/Octavian.jl#42]
| Package                                                                                                             | Function           | `export`ed? |
| -------------------------------------------------------------------------- | --------------- | ------------ |
| [Gaius.jl](https://github.com/MasonProtter/Gaius.jl)                                       | `Gaius.mul!`     | no                |
| [Octavian.jl](https://github.com/JuliaLinearAlgebra/Octavian.jl)                     | `matmul!`         | yes              |
| ~~[PaddedMatrices.jl](https://github.com/chriselrod/PaddedMatrices.jl)~~ | ~~`matmul!`~~ | ~~yes~~     |
| ~~[StrideArrays.jl](https://github.com/chriselrod/StrideArrays.jl)~~              | ~~`matmul!`~~ | ~~yes~~     |

We should come up with some different names.

I think the implementation that is currently the fastest should get the name `matmul!`. IIRC, PaddedMatrices currently has the fastest implementation. So we should keep the name `matmul!` for PaddedMatrices, and come up with a different name for Octavian.jl. Maybe `gemm!`? Or `matrix_mul!`?

---

For reference, the `LinearAlgebra` standard library `export`s the following names, so we should not `export` any of them from our own packages:
- `axpby!`
- `axpy!`
- `lmul!`
- `mul!`
- `rmul!`

**Comment by DilumAluthge** [comment]
@chriselrod After we merge https://github.com/JuliaLinearAlgebra/Octavian.jl/pull/41, are you still going to have a matrix multiplication function in StrideArrays? Or are you going to remove it from StrideArrays?

**Comment by chriselrod** [comment]
Given the PR to move the implementation, Padded/Stride arrays would use Octavian's method

**Comment by chriselrod** [comment]
> @chriselrod After we merge #41, are you still going to have a matrix multiplication function in StrideArrays? Or are you going to remove it from StrideArrays?

I'll remove it.

**Comment by DilumAluthge** [comment]
> > @chriselrod After we merge #41, are you still going to have a matrix multiplication function in StrideArrays? Or are you going to remove it from StrideArrays?
> 
> I'll remove it. And from PaddedMatrices too, but StrideArrays is its successor.

I've removed StrideArrays from the table.

So https://github.com/JuliaLinearAlgebra/Octavian.jl/pull/41 will move the StrideArrays matmul into Octavian.

If you're also removing the PaddedMatrices matmul, are you going to put that implementation somewhere else?

**Comment by chriselrod** [comment]
No, I'll delete it.

**Comment by DilumAluthge** [comment]
> No, I'll delete it.

Oh, I see. Is the implementation in StrideArrays (soon to be Octavian) faster than the implementation in PaddedArrays?

**Comment by chriselrod** [comment]
Yes, especially at small sizes.

**Comment by DilumAluthge** [comment]
I've removed PaddedMatrices from the table, which means the issue basically resolved itself.

I'll leave it open until the surgeries on StrideArrays and PaddedMatrices are complete.
