### ISSUE TITLE
Documenting Octavian behavior with @threads

### ISSUE THREAD

**Issue by jlchan** [JuliaLinearAlgebra/Octavian.jl#79]
It seems from https://discourse.julialang.org/t/odd-benchmarktools-timings-using-threads-and-octavian/59838/5 that `matmul!` doesn't play well with `@threads`. Would it be useful to have this in the docs, maybe just as a warning or `!!! note`? 

I'm happy to add this if it seems useful.

**Comment by chriselrod** [comment]
Yeah, it's worth noting.

**Comment by jlchan** [comment]
Addressed in https://github.com/JuliaLinearAlgebra/Octavian.jl/pull/80
