### ISSUE TITLE
is this a typo in the doc of matmul!

### ISSUE THREAD

**Issue by JianghuiDu** [JuliaLinearAlgebra/Octavian.jl#81]
```julia
matmul!(C, A, B[, α, β, max_threads])
Calculates C = α * A * B + β * C in place, overwriting the contents of A. 
```
### _overwriting the contents of A._
Not **_C_**? Also why is there a bracket in side?

**Comment by chriselrod** [comment]
Yes, it is a typo. It overwrites the contents of `C`, not of `A`.

The brackets meant to say that those are optional positional arguments. Perhaps it should instead show their defaults to make that more clear.

**Comment by JianghuiDu** [comment]
Also I noticed that C, A and B must all be matrix in matmul!. Whereas the LinearAlgebra mul! accepts vectors for C and B. Is there a plan to support matrix vector multiplication?

**Comment by chriselrod** [comment]
Yes. It should be much simpler than matrix-matrix.
